apiVersion: v1 
kind: ConfigMap
metadata: 
  name: users-api-config
  namespace: users-api
data: 
  PORT: "3000"
  HOST: "0.0.0.0"
  DATABASE_HOST: "10.0.0.254"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "otus_users_db"